import type { ComponentProps } from "react";
import {
  Activity,
  AlertTriangle,
  ArrowUp,
  BadgeCheck,
  Beaker,
  BicepsFlexed,
  Bot,
  Brush,
  Camera,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  Circle,
  CircleAlert,
  CircleCheck,
  ClipboardList,
  Droplet,
  Download,
  Eraser,
  Eye,
  FileSpreadsheet,
  FileText,
  FlaskConical,
  Flower2,
  Hand,
  House,
  Image,
  Info,
  Leaf,
  Lightbulb,
  Link2Off,
  LocateFixed,
  MapPin,
  MessageCircle,
  Mic,
  Package,
  Palette,
  Pause,
  Pencil,
  Puzzle,
  Play,
  Plus,
  RefreshCw,
  Save,
  ScanLine,
  Search,
  ShieldCheck,
  Sparkles,
  Star,
  SprayCan,
  Sun,
  Syringe,
  Target,
  Timer,
  Trash2,
  Upload,
  Volume2,
  VolumeX,
  WandSparkles,
  Waves,
  X,
  XCircle,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS = {
  activity: Activity,
  alert: AlertTriangle,
  "arrow-up": ArrowUp,
  approved: BadgeCheck,
  beaker: Beaker,
  bot: Bot,
  brush: Brush,
  bubbles: Waves,
  camera: Camera,
  chart: ChartNoAxesCombined,
  check: Check,
  "chevron-down": ChevronDown,
  "check-circle": CircleCheck,
  circle: Circle,
  "circle-alert": CircleAlert,
  clipboard: ClipboardList,
  droplet: Droplet,
  download: Download,
  eraser: Eraser,
  eye: Eye,
  file: FileText,
  "file-spreadsheet": FileSpreadsheet,
  flask: FlaskConical,
  flower: Flower2,
  hand: Hand,
  home: House,
  image: Image,
  info: Info,
  leaf: Leaf,
  lightbulb: Lightbulb,
  "link-off": Link2Off,
  locate: LocateFixed,
  map: MapPin,
  message: MessageCircle,
  mic: Mic,
  muscle: BicepsFlexed,
  package: Package,
  palette: Palette,
  pause: Pause,
  pencil: Pencil,
  puzzle: Puzzle,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  save: Save,
  scan: ScanLine,
  search: Search,
  shield: ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  spray: SprayCan,
  sun: Sun,
  syringe: Syringe,
  target: Target,
  timer: Timer,
  trash: Trash2,
  upload: Upload,
  volume: Volume2,
  "volume-off": VolumeX,
  wand: WandSparkles,
  x: X,
  "x-circle": XCircle,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type SemanticIconName = keyof typeof ICONS;

export function SemanticIcon({
  name,
  "aria-hidden": ariaHidden = true,
  ...props
}: { name: SemanticIconName } & Omit<ComponentProps<LucideIcon>, "name">) {
  const Icon = ICONS[name];
  return <Icon aria-hidden={ariaHidden} {...props} />;
}
